# Generated by Django 5.2.3 on 2025-11-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='img',
            field=models.URLField(default='https://www.foodiesfeed.com/wp-content/uploads/2023/06/burger-with-melted-cheese.jpg'),
        ),
    ]
